name: 'Tests'

on:
  - push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -la
      - run: |
          cat requirements.txt
      - run: |
          python -v
      - run: |
          python3 -v
      - name: install deps
        run: |
          python -m pip install < requirements.txt
      - name: run molecule
        run: |
          molecule test
