name: 'Tests'

on:
  - push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          python -m pip install < requirements.txt
      - uses: gofrolist/molecule-action@v2
