name: 'Tests'

on:
  - push

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - uses: actions/checkout@v2
      - run: |
          python2 -V

      - run: |
          python -V
          
      - name: install venv
        run: |
          python2 -m pip install virtualenv
      - name: venv
        run: |
          python2 -m virtualenv venv
      - name: using venv
        run: |
          source venv/bin/activate
      - name: install deps
        run: |
          python2 -m pip install -r requirements.txt
      - name: run molecule
        run: |
          molecule test
