name: 'Tests'

on:
  - push

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: venv
        run: |
          python2 -m virtualenv venv
      - name: install deps
        run: |
          source venv/bin/activate && python2 -m pip install -r requirements.txt
      - name: run molecule
        run: |
          source venv/bin/activate && molecule test
